### ISSUE TITLE
Rack v1: compile error on Windows and Linux

### ISSUE THREAD

**Issue by cschol** [JerrySievert/CharredDesert#11]
Compile error on Windows and Linux platforms. Mac works correctly.

```
src/controller/Carbon.cpp: In member function ‘virtual void CarbonModule::process(const rack::engine::Module::ProcessArgs&)’:
src/controller/Carbon.cpp:29:9: error: ‘isnan’ was not declared in this scope
     if (isnan(out)) {
         ^~~~~
src/controller/Carbon.cpp:29:9: note: suggested alternative:
In file included from /home/cschol/src/Rack-1.0/dist/Rack-SDK/include/common.hpp:10:0,
                 from /home/cschol/src/Rack-1.0/dist/Rack-SDK/include/rack.hpp:4,
                 from src/controller/../CharredDesert.hpp:1,
                 from src/controller/Carbon.hpp:1,
                 from src/controller/Carbon.cpp:1:
/usr/include/c++/7/cmath:639:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^~~~~
```

**Comment by JerrySievert** [comment]
odd, as you noted it isn't an issue with clang++ (macOS), and wasn't an issue with g++ when compiling against 0.6 (the only changes were rack specific, see https://github.com/JerrySievert/CharredDesert/blob/master/src/controller/Carbon.cpp#L26) - was there a version change for g++ that could affect this, or a compilation directive changing the c++ version number compiled against?

**Comment by cschol** [comment]
I compile with g++ on Ubuntu 18.04. Andrew still builds with an older version on 16.04, but will switch soon. I think this is related to some changes Andrew made with  namespacing in 1.0. I have seen a few issues now where clang works fine, but g++ needs extra headers or namespacing.

**Comment by JerrySievert** [comment]
I'm going to guess that there was a removal of `using namespace std;` somewhere - regardless, I made the change (`std::isnan`) so it should be happier for you (I hope!).

**Comment by SteveRussell33** [comment]
Confirming that commit aba739eb74fc8d3c276cc7163ec0ad722d98431b builds correctly on Win 10 and loads correctly in latest V1 build

**Comment by JerrySievert** [comment]
thanks @SteveRussell33 !
